# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

jobs:
  - job: BuildAPI
    displayName: "Build and Test API"
    steps:
      - task: UseDotNet@2
        displayName: "Install SDK"
        inputs:
          version: 9.x
          includePreviewVersions: true
          performMultiLevelLookup: true
      - task: DotNetCoreCLI@2
        displayName: "Build App"
        inputs:
          command: build
          arguments: '--configuration $(buildConfiguration)'
          
      - task: DotNetCoreCLI@2
        displayName: 'dotnet test'
        inputs:
          command: 'test'
          arguments: '--configuration $(buildConfiguration) --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura'
          publishTestResults: true
          projects: 'MyTestLibrary' # update with your test project directory

      - task: PublishCodeCoverageResults@2
        displayName: 'Publish code coverage report'
        inputs:
          codeCoverageTool: 'Cobertura'
          summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'
      - task: DotNetCoreCLI@2
        displayName: "Publish App"
        inputs:
          command: publish
          arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
          zipAfterPublish: true
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)' 
          artifactName: 'myWebsite'
  - job: BuildFrontend
    displayName: "Build and Test Frontend"
    steps:
      - task: CmdLine@2
        inputs:
         script: ls
      - task: Npm@1
        inputs:
         command: install