# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: "Install SDK"
  inputs:
    version: 9.x
    includePreviewVersions: true
    performMultiLevelLookup: true
- task: DotNetCoreCLI@2
  displayName: "Build App"
  inputs:
    command: build
    arguments: '--configuration $(buildConfiguration)'
